services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: kansha
      POSTGRES_PASSWORD: Kansha5199@
      PGDATA: /data/
    volumes:
      - db:/data/
    ports:
      - "5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: